export const ERROR_CODES = {
    USER_EXISTS: 'USER_EXISTS',// 用户已存在
    USER_NOT_FOUND: 'USER_NOT_FOUND', // 用户不存在
    INVALID_PASSWORD: 'INVALID_PASSWORD', // 密码错误
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR', // 错误
    INVALID_TOKEN: 'INVALID_TOKEN', // 用户已失效，请重新登录
    INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE' // 余额不足
};
